apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan
spec:
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
      app: loan
  template:
    metadata:
      labels:
        app: loan
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: In
                values:
                - 'true'
      containers:
      - name: loan
        image: ags131/loan
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "200Mi"
            cpu: "100m"
        env:
        - name: SETTINGS
          value: /data/settings
        ports:
        - name: http
          containerPort: 5000
        volumeMounts:
        - name: loan
          mountPath: /data
      volumes:
      - name: loan
        persistentVolumeClaim:
          claimName: loan
