apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loan
bases:
- site
- nuke-announcer
- postgres
- vk
resources:
- ingress.yml
- cronjob-seasonal-scoreboard.yml
- ns-loan.yml
