apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
resources:
- cronjob-sync.yml
commonLabels:
  group: stats-public
nameSuffix: -public
patchesStrategicMerge:
- patch-carbonapi.yml
configMapGenerator:
- name: go-carbon
  files:
  - configs/go-carbon.conf
  - configs/storage-aggregation.conf
  - configs/storage-schemas.conf
- name: carbonapi
  files:
  - configs/carbonapi.yml