bases:
- ../server-base
commonLabels:
  server: server2
namePrefix: server2-
configMapGenerator:
- name: config
  files:
  - config.yml=config/config.yml
  - market.yml=config/market.yml
patchesStrategicMerge:
- node-patch.yml
- ingress.yml