apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: NotIn
                values:
                - 'true'
      containers:
      - name: mongo
        image: mongo:3.6
        resources:
          requests:
            memory: "200Mi"
            cpu: "50m"
          limits:
            memory: "1Gi"
            cpu: "100m"
        ports:
        - name: tcp
          containerPort: 27017
        volumeMounts:
        - name: db
          mountPath: /data/db
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: mongo-db
