apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
spec:
  template:
    spec:
      containers:
        - name: flux
          args:
            - --manifest-generation=true
            - --memcached-hostname=memcached.flux
            - --memcached-service=
            - --ssh-keygen-dir=/var/fluxd/keygen
            - --git-branch=master
            - --git-path=servers
            - --git-user=ags131
            - --git-email=ags131@users.noreply.github.com
            - --git-url=git@github.com:ags131/screepsplus-k8s
            - --git-poll-interval=1m