apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: toolbox
  name: toolbox
  namespace: server2
spec:
  selector:
    matchLabels:
      app: toolbox
  template:
    metadata:
      labels:
        app: toolbox
    spec:
      containers:
      - command:
        - bash
        args:
        - -c
        - while true; do sleep 10000; done
        image: ubuntu #ags131/screeps-toolbox
        imagePullPolicy: Always
        name: toolbox
        resources: {}
        volumeMounts:
        - mountPath: /screeps
          name: main
        - mountPath: /screeps/history
          name: history
      volumes:
      - persistentVolumeClaim:
          claimName: screeps
        name: main
      - hostPath:
          path: /srv/main/history
          type: ""
        name: history