apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: screeps-processors
  name: screeps
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: screeps-processors
  template:
    metadata:
      labels:
        app: screeps-processors
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: server-secrets
            optional: false
        image: screepers/screeps-launcher
        args:
        - --modules
        - processor
        name: screeps
        resources: {}
        volumeMounts:
        - mountPath: /screeps/config.yml
          name: vol1
          subPath: config.yml
        - mountPath: /screeps/mods/morgan.js
          name: vol1
          subPath: mod-morgan.js
        - mountPath: /screeps/market.yml
          name: vol1
          subPath: market.yml
        - mountPath: /screeps
          name: main
      volumes:
      - configMap:
          defaultMode: 292
          name: config
          optional: false
        name: vol1
      - hostPath:
          path: /srv/main
          type: ""
        name: main
