apiVersion: v1
kind: Service
metadata:
  name: screeps
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 21025
  selector:
    app: screeps
  type: ClusterIP
# --- # Done in Traefik now
# apiVersion: v1
# kind: Service
# metadata:
#   name: screeps-lb
# spec:
#   ports:
#   - name: http
#     port: 21025
#     protocol: TCP
#     targetPort: 21025
#   selector:
#     app: screeps
#   type: LoadBalancer

