apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
      service: screeps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb
        service: screeps
    spec:
      nodeSelector:
        screepspl.us/server: server0
      containers:
      - image: mongo
        name: mongodb
        ports:
        - containerPort: 27017
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongo-data
      terminationGracePeriodSeconds: 30
      volumes:
      - persistentVolumeClaim:
          claimName: mongodb
        name: mongo-data
