apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
commonLabels:
  group: grafana-public
nameSuffix: -public
configMapGenerator:
- name: grafana
  files:
  - configs/grafana.ini