apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbonapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: carbonapi
  template:
    metadata:
      labels:
        app: carbonapi
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: In
                values:
                - 'true'
      containers:
      - name: carbonapi
        image: ags131/carbonapi
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "1Gi"
            cpu: "100m"
        ports:
        - name: http-query
          containerPort: 8081
