apiVersion: v1
kind: Service
metadata:
  name: go-carbon
spec:
  selector:
    app: go-carbon
  ports:
  - name: http-query
    port: 8080
    targetPort: http-query
  - name: tcp-intake
    port: 2003
    targetPort: tcp-intake
