bases:
- ../server-base
commonLabels:
  server: server1
namePrefix: server1-
configMapGenerator:
- name: config
  files:
  - config.yml=config/config.yml
  - market.yml=config/market.yml
patchesStrategicMerge:
- node-patch.yml