apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nuke-announcer
  name: nuke-announcer
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
